TODO-004: Update multiple task statuses
fravila08/To-Do-Applicaiton pull request #5
Opened 2023-02-10 21:47 UTC by fravila08

Acceptance Criteria

Given a user opens the TODO app
When the tasks are displayed
Then an unchecked check box appears at the end of each task
And a "Change status" button is displayed on the top left of the page
And the "Change status" button is disabled

Given a user clicks on one or more check boxes
Then the "Change status" button is changed to active

Given the "Change status" button is active
When the button is clicked
Then the status of the task is changed (Complete <-> Pending)

Given a task
When the status changes between complete and pending
Then the task moves to the appropriate section

https://user-images.githubusercontent.com/105952966/218205014-1d364b5f-29ae-4503-ad96-d8321323bc3f.mov

2023-02-14 09:05 UTC, Kotauror requested changes
As always this is a solid submission. I appreciate a smaller PR too 👍 

The two longer comments that I made (in `to_do_client/src/__tests__e2e_/ChangingMultipleTaskStatusE2E.test.tsx` and `to_do_server/to_do_app/urls.py`) are there to challenge you, especially the one about REST API design. I don't expect you to do the entire refactoring now, the PR approval is not dependent on it, it's extra stuff. 

Please do address the other comments that I made though, they are smaller but important.

2023-02-14 17:44 UTC, fravila08 commented on to_do_client/src/components/Header.tsx
> +            CS
Lol touch I'll update it 😆

2023-02-14 17:52 UTC, fravila08 commented on to_do_server/to_do_app/views.py
> +class Multi_task_handler(APIView):
I wanted to separate these into separate classes to make my code easier to read and follow. It could get really bunched up and "nasty" once I receive a put request for updating the class title later on causing me to place multiple if and else conditionals with separate return functions. 

I'm not sure if I'm interpreting this correctly but would I want to keep these separate to allow for the application to grow without creating too many dependencies?

2023-02-14 18:06 UTC, fravila08 commented on to_do_server/to_do_app/urls.py
> +    path('changemultiple', Multi_task_handler.as_view(), name='multiple'),
That was a good read, I believe I applied the rest principles correctly as far as the naming conventions, but, I definitely have lots to learn about error handling in API's.

2023-02-14 18:09 UTC, fravila08 commented on to_do_client/src/__tests__e2e_/ChangingMultipleTaskStatusE2E.test.tsx
> +  describe("Creating a Task", () => {
Sorry I need to change the describe and it block of this test. The test is choosing 3 tasks that exist and then moving them into a separate section. I will adjust it and make it independent from the scripts.

2023-02-14 19:46 UTC, nadiacollado commented on to_do_client/src/__tests__int_/HeaderINT.test.tsx
>    describe("createTask()", () => {
This is nitpicky but can we change the description to "returns true if a task is a created" because we're not actually checking whether the ID is being returned. If you want to include that check then I'd add an assertion for the id

2023-02-14 19:55 UTC, nadiacollado commented on to_do_client/src/__tests__unit_/HeaderUnit.test.tsx
For the first two tests, can you specify what is being returned?

2023-02-14 19:57 UTC, nadiacollado commented on to_do_client/src/__tests__unit_/TaskRendererUnit.test.tsx
> +    let completed: boolean = true;
You should be able to write this as: `let completed = true`. Typescript is able to infer the type for that :)

2023-02-14 19:58 UTC, nadiacollado commented on to_do_client/src/__tests__unit_/TaskRendererUnit.test.tsx
> +    const setAllTasks = (tl: ITask[]) => {
What does `tl` stand for? Probably best to spell it out completely

2023-02-14 19:58 UTC, nadiacollado commented on to_do_client/src/__tests__unit_/TaskRendererUnit.test.tsx
> +    const setSelected = (nl: number[]) => {
Same for `nl`

2023-02-14 20:01 UTC, nadiacollado commented on to_do_client/src/__tests__unit_/TaskUnit.test.tsx
>        allTasks = tl;
Please spell out :)

2023-02-14 20:01 UTC, nadiacollado commented on to_do_client/src/__tests__unit_/TaskUnit.test.tsx
>    });
Same thing for this test as well, include what is being returned in the describe block

2023-02-14 20:18 UTC, nadiacollado commented on to_do_client/src/components/Header.tsx
> +export const changeSelectedTasks = async (lst: number[]) => {
is this meant to be `list`?

2023-02-14 20:18 UTC, nadiacollado commented on to_do_client/src/components/Header.tsx
> +  let resposne = await axios.put("tasks/", { selected: lst });
Typo: `response`

2023-02-14 20:18 UTC, nadiacollado commented on to_do_client/src/components/Header.tsx
> +    return mylist.length < 1;
camelCase here :)

2023-02-15 07:55 UTC, Kotauror approved these changes
I've added one more small request to `to_do_client/src/__tests__e2e_/ChangingMultipleTaskStatusE2E.test.tsx`, but the change in the test is exactly what I expected. 

I also gave you some tips for Task handlers shall you decide to refactor them in the future.

2023-02-15 07:55 UTC, Kotauror commented on to_do_server/to_do_app/views.py
> +class Multi_task_handler(APIView):
Thank you for explaining your reasoning, I surely see your point and it's a trade-off situation and thinking about where do I best locate which element of the logic. It's probably the hardest part of being a programmer! 

I'd say if you think that it works for you now, keep it this way and see in the future if it does feel the same as time passes. If you feel like you'd like to explore the refactoring idea a bit more, here are two approaches that I've been thinking about.

1. I agree that the if/else statement in the single task handler might make it less clean. But you could potentially keep one handler and not have the if/else there. You could have one handler if the functions run for both single and multiple arguments. This way, you could move away the if/else logic out of view. For example, you'd have a single `update_tasks_completed_status` function that would accept an array of tasks. That could be one task as well as multiple. Then, inside of that function, there would be an iteration of the list that would again work both for one as well as for multiple items. 

2. There is this _thing_ called pattern matching in some of the languages - I've used it in Elixir in the past. It's when you define a few functions with the same name (eg. `put`), but they do different things depending on the arguments! (that's quite cool). Check out this Elixir article [here](https://inquisitivedeveloper.com/lwm-elixir-23/) - especially around this example: 
```
def do_something([head | tail], {_, second}), do: {head, tail, second}
def do_something([], {first, _}), do: first
def do_something([]), do: 3
```
I have no idea if Python has the option to do it and if it's[ idiomatic to Python](https://stackoverflow.com/questions/84102/what-is-idiomatic-code) (probably not!). But when you have a moment, check it out, it will surely be an interesting learning experience.

2023-02-15 07:55 UTC, Kotauror commented on to_do_client/src/__tests__e2e_/ChangingMultipleTaskStatusE2E.test.tsx
> +  describe("Creating a Task", () => {
No need to be sorry! :)

2023-02-15 07:55 UTC, Kotauror commented on to_do_client/src/__tests__e2e_/ChangingMultipleTaskStatusE2E.test.tsx
>      it("will create and display new task under `pending`", async () => {
I'd do one more change here - put the `test creating a task` into a variable and use it on lines 26 and 46. You'll have one place to change in the future, not two, you'll avoid magic strings and the assertion will be easier to understand.

2023-02-15 19:59 UTC, fravila08 commented on to_do_server/to_do_app/tests/test_views.py
> +
I totally missed it and forgot to capitalize.

2023-02-15 20:29 UTC, nadiacollado commented on to_do_client/src/__tests__e2e_/ChangingMultipleTaskStatusE2E.test.tsx
> +      let textToDisplay = 'test creating a task'
Nice

2023-02-15 20:57 UTC, nadiacollado commented on to_do_client/src/__tests__unit_/HeaderUnit.test.tsx
> +    it("returns a dictionary with the keys of itemCreated with a boolean value and id with a number value", async () => {
For this test, we're checking a happy path, so I would specify that in the description, so: "returns a dictionary with itemCreated and id as keys, where itemCreated's value is true and id's value is the task's id"

2023-02-15 20:59 UTC, nadiacollado commented on to_do_client/src/__tests__unit_/HeaderUnit.test.tsx
> +    const setSelectedTasks = (numberList: number[]) => {
might be nice to have something a little more specific like `idList` or `taskIdList` but this works!

2023-02-15 21:00 UTC, nadiacollado approved these changes

2023-02-15 21:06 UTC, merged